### ISSUE TITLE
Update to include .net standard 2.0

### ISSUE THREAD

**Issue by lukevp** [FusionAuth/fusionauth-netcore-client#13]
For libraries it's preferred that they target .net standard rather than .net core.  If they target .net standard, they can be used in full framework apps above 4.7.1 and in universal apps, but if they target .net core they must run in the .net core runtime.

**Comment by robotdan** [comment]
Thanks @lukevp this is an area where it seems like we get different input. 

The goal is to make the Net Core client work in as many environments as possible. Windows, Mac, Linux, Mono, etc. 

We currently target NetCore App 2.1 and 2.2. 

```
<TargetFrameworks>netcoreapp2.1;netcoreapp2.2</TargetFrameworks>
```

We had been targeting NetStandard as well, but once we introduced support for the `PATCH` HTTP method, we removed NetStandard because it does not include the `HttpClient.PatchAsync` method.

Do you know of another option to support NetStandard and also support the HTTP Patch method in .NET?

**Comment by lukevp** [comment]
@robotdan first of all, thanks for the great app!

Adding .net standard will not reduce support but will just add support for full framework .net.  While it's true that .net core runs on Windows, a lot of .net code is stuck in Full Framework land right now.  For example, any use of DataSets, or Microsoft Message Queues, or WCF, WPF, WinForms, etc, will tie you to full framework.  Microsoft is working around this with .NET 5 and the windows compatibility packs and shims which open up more use cases of .NET Core with legacy MS tech, but it's not fully there yet.  So being .net standard will help with this use case, and also for UWP apps for those who might have made some of those.

The only downside to adding .net standard support is that the .nupkg is larger and that you have to maintain a larger compatibility base but since a lot of this lib is wrapper and codegen around a REST client, I personally don't view this is a major issue.

I opened PR #14 to add back in support for .net standard, with a fix for the PATCH method.  There's no helper PatchAsync or an entry in the HttpMethod class for this functionality in NetStandard 2.0, but those are really just convenience around static strings, so you can get by using the constructor of HttpMethod that takes a string instead.

I tested this with my self hosted fusionauth install and it passed test case Patch_Application_Test.

I hope this is helpful, please feel free to comment on the PR if you see any issues, and let me know if I can be of any other help on the .net side.  

I've just started using Fusion but it's been great so far! One thing I noticed is that the error messages are very nested and difficult to extract, but I can open a separate issue to discuss this and ways it might be more ".net friendly".

**Comment by lukevp** [comment]
@robotdan  bump on this and PR #14  any thoughts?

**Comment by robotdan** [comment]
Hi @lukevp thanks for the bump, we'll see if we can spend a few minutes on this to come to a decision. Thanks for your insights into the .NET world..  :-)

**Comment by robotdan** [comment]
Accepted PR, now targeting:

```
<TargetFrameworks>netstandard2.0,netstandard2.1,netcoreapp2.1;netcoreapp3.1</TargetFrameworks>
```

**Comment by lukevp** [comment]
Lowering the LangVersion is just for the compile step, not for runtime compatibility, so it's only a concern for your team or contributors to this client library, not consumers/end users of the library.  LangVersion is just a directive to the C# compiler on what language features you are using.  Once it compiles down to the .net common intermediate language it's the same level of compatibility as your target framework.  Typically people raise up the LangVersion as newer versions of Visual Studio and C# come out so they can take advantage of newer language features.

I'll give the library a try this weekend, if I forget to follow up just ping me and I'll let you know how it went.

Another standardization thing you might consider is your current use of newtonsoft.json.   The history of that library is pretty interesting.  It's one of the top libraries in the .net ecosystem.  The original developer, James King, wrote the library independently, but later was hired by Microsoft.  He works on the team that built System.Text.Json, which is the official successor, included in ASP.NET Core, and is faster than the old library.  So you may consider taking a dependency on that library instead, it is compatible with all the versions that this library is targeting as well.  I'm not sure what effort it would be to migrate to it though so that would be up to you if it was worth the effort to do that now.

Here's the library: https://www.nuget.org/packages/System.Text.Json

**Comment by robotdan** [comment]
Thanks @lukevp for the explanation, very helpful. I like the idea of swapping NewtonSoft for "new hotness". 

I don't know what the level of effort will be, so I'll open an issue to track it for now. 

Thanks for your contributions to the FusionAuth community!
