### ISSUE TITLE
Importing a user without a password

### ISSUE THREAD

**Issue by ashokgelal** [FusionAuth/fusionauth-netcore-client#23]
About half of our users don't have passwords set as they are authenticated via third party ID providers such as Google. While importing users from an existing system, I'm not setting anything for `password` and `salt` fields, which is causing the import to throw `You must specify the [user.password] property for each user.` error (using the FA's .net client). What would I set for password and salt in this case? Thank you!

**Comment by robotdan** [comment]
https://fusionauth.io/community/forum/topic/178/how-do-i-handle-users-without-passwords-during-import

**Comment by ashokgelal** [comment]
Thank you!

**Comment by robotdan** [comment]
Answered as well.
