### ISSUE TITLE
Release 1.21.0 to Nugget

### ISSUE THREAD

**Issue by EPRenaud** [FusionAuth/fusionauth-netcore-client#35]
Hello,

The 1.21.0 release includes bug fixes that my company would be keen on using. Would it be possible to deploy this release to Nugget. Indeed, it's still blocked at the 1.20 version https://www.nuget.org/packages/FusionAuth.Client/

Cheers!

**Comment by robotdan** [comment]
Thanks for letting us know @EPRenaud  - our Nuget API key had expired, so it didn't get published during the release. We've corrected this and have pushed the release. 

https://www.nuget.org/packages/FusionAuth.Client/

**Comment by robotdan** [comment]
Please re-open if you you run into issues with it.

**Comment by EPRenaud** [comment]
Cheers!
