### ISSUE TITLE
ForgotPassword flow returning 401

### ISSUE THREAD

**Issue by BenTMatthews** [FusionAuth/fusionauth-netcore-client#39]
I posted about it here, but I am pretty sure this is an issue: https://fusionauth.io/community/forum/topic/920/duplicate-email-verification-emails-being-sent-and-forgot-password-401

Ignoring the part about duplicate emails being sent (that might still be something on my end), but the forgot password issue seems legit. 

```
                FusionAuthClient client = new FusionAuthClient(_authSettings.ApiKey, _authSettings.Host, _authSettings.TenantId);
                
                ForgotPasswordRequest forgotReq = new ForgotPasswordRequest();
                forgotReq.applicationId = new Guid(_authSettings.ApplicationId);
                forgotReq.email = model.Email;
                forgotReq.username = model.Email;

                ClientResponse<ForgotPasswordResponse> forgotResp = await client.ForgotPasswordAsync(forgotReq);
```
                
This comes back with a 401 response, indicating the apikey is incorrect, however the same key is used in all other calls through the library and do not give 401. I have tried multiple configurations on the application and tenant level with no luck. I verified all values are correct in the settings.

**Comment by robotdan** [comment]
Can you confirm your API key has access to this API? `/api/user/forgot-password`

**Comment by BenTMatthews** [comment]
@robotdan 

Holy crap, I can't believe I didn't think to look at the key level. Thank you!
