### ISSUE TITLE
Login doesn't contain the User Object if Email is not verified

### ISSUE THREAD

**Issue by anubhavranjan** [FusionAuth/fusionauth-netcore-client#4]
### Description
I have added Users whose Emails have not been verified.
Now when trying to Login, the API is not returning the User.
Rather just the StatusCode 212
The previous version was working perfectly fine but with the latest change, it's not.

### Expected behavior
After performing the Login, I should get the User Object and statusCode 212

### Screenshots
![image](https://user-images.githubusercontent.com/6568809/68988808-3f007300-0863-11ea-978d-6e41d9eb9538.png)

### Platform
 - Server: IIS Express, .Net Core
 - OS: Windows 10
 - Browser + version: Microsoft Edge (Insider)
 - FusionAuth version 1.10.1 

### Additional context
As seen in the screenshot, the statusCode is 212 but there are no additional data provided.
In the earlier version, this issue was not there.

**Comment by anubhavranjan** [comment]
The issue still exists in version 1.11.0

**Comment by robotdan** [comment]
@tyduptyler13 or @matthew-altman want to take a look when you have a free moment?

**Comment by tyduptyler13** [comment]
I found that our default rest client wasn't tolerant of other 200 codes. I fixed this and it should be released in the next FusionAuth release.
