### ISSUE TITLE
Missing fields in token from login user response. 

### ISSUE THREAD

**Issue by mohed** [FusionAuth/fusionauth-netcore-client#47]
Hello. 

When calling the API directly from Postman on the login endpoint, the token in the response has some additional fields compared to the token one receives via using the library. The important one for us is the "aud" parameter.  Is there a way to include the "aud" parameter in the Jwt token in the successResponse of the client.

**Comment by mohed** [comment]
Providing application id solved it. Sorry to bother you.

**Comment by mooreds** [comment]
Glad you figured it out. This might be useful reading as well (if you haven't seen it already): https://fusionauth.io/docs/v1/tech/core-concepts/authentication-authorization/ as that talks a bit more about why a user can login but sometimes not receive certain claims.
