### ISSUE TITLE
Issues with Patch support

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-netcore-client#5]
When Patch support was added it looks like we broke compatibility with the lowest version of .NET. 

We are currently supporting `netcoreapp2.0, netcoreapp2.1, netcoreapp2.2, netstandard2.0` - I don't know if that is the problem or not, but it looks like the `PatchAsync` method is not available in our current dependency version of of `System.Net.Http`. 

The project wasn't building due to some syntax errors and this dependency issue. Perhaps we have an issue in our build and release - I don't know how it would have been packed and published as is. 

I think the `PatchSync` wasn't added until 2.1
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.patchasync?view=netcore-2.1

We'll either have to upgrade our min target or add a poly fill, or remove Patch support in this client. 
https://stackoverflow.com/questions/26218764/patch-async-requests-with-windows-web-http-httpclient-class/26218765#26218765

We need to ensure we all have IJ Rider or other C# editor installed so we can review changes for syntax errors and compile issues, etc.

**Comment by robotdan** [comment]
While we're in this client, we can take a look at this issue as well
https://github.com/FusionAuth/fusionauth-issues/issues/438

**Comment by robotdan** [comment]
I fixed a few minor issues under commit f8c5327d2a0343f2f4f45cf3ff9d93c064e5bf49 - we just need to figure out what the min. version we can support and still get `PatchAsync`.

**Comment by lukevp** [comment]
@robotdan  you can probably close this issue after merging #14 .
