### ISSUE TITLE
replace duende in skoruba

### ISSUE THREAD

**Issue by weedkiller** [FusionAuth/fusionauth-netcore-client#50]
Hello how do we replace or integrate into Skoruba

issue ref: https://github.com/skoruba/IdentityServer4.Admin/issues/718

**Comment by mooreds** [comment]
Hiya @weedkiller . This doesn't seem like a bug in this client library, but rather a support request. Please open a ticket in the FusionAuth forum: https://fusionauth.io/community/forum/ or, if you have a paid support plan, open a support ticket: https://account.fusionauth.io/account/support/

Please be aware that FusionAuth is not open source and any use of it is governed by the license. Here's the license: https://fusionauth.io/license/ and here's an FAQ about the license and usage: https://fusionauth.io/license-faq/

Closing this ticket, hope to see you on the forum!
