### ISSUE TITLE
JsonSerializationException in FusionAuthSyncClient.RetrieveTenants()

### ISSUE THREAD

**Issue by BobbyWhiskey** [FusionAuth/fusionauth-netcore-client#51]
I have a serialization error when i call FusionAuthSyncClient.RetrieveTenants().
I use the latest version of the nuget package (1.29.1) on the API version 1.30.1.

I have investigated the problem and tested the same code but on the API version 1.29.4 and it works perfectly. 
Is it possible the response of this endpoint had changed in version 1.30 and the client was not updated?

Here is the exception:
> Newtonsoft.Json.JsonSerializationException: Could not convert string 'audit-log.create' to dictionary key type 'io.fusionauth.domain.event.EventType'. Create a TypeConverter to convert from the string to the key type object. Path 'tenants[0].eventConfiguration.events['audit-log.create']', line 1, position 1083.
 ---> Newtonsoft.Json.JsonSerializationException: Error converting value "audit-log.create" to type 'io.fusionauth.domain.event.EventType'. Path 'tenants[0].eventConfiguration.events['audit-log.create']', line 1, position 1083.
 ---> System.ArgumentException: Requested value 'audit-log.create' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)

**Comment by mooreds** [comment]
This looks like we need to publish a new version of the fusionauth client library (we added some new events in 1.30.)

**Comment by mooreds** [comment]
@BobbyWhiskey please try the latest version of the client (1.30.2); I just published it. Let me know if that doesn't resolve the error, please. (It should be validated and listed in a few minutes.)

https://www.nuget.org/packages/FusionAuth.Client/

**Comment by BobbyWhiskey** [comment]
@mooreds I updated the client and it works perfectly now. Thanks for the quick fix!
