### ISSUE TITLE
How do add user info group

### ISSUE THREAD

**Issue by MohMehrnia** [FusionAuth/fusionauth-netcore-client#54]
Hi, How do add a user info group?

**Comment by mooreds** [comment]
hi @MohMehrnia ,

Thanks for using FusionAuth. The GitHub issues are best for bugs with reproduction steps.

It sounds like you are looking for support. You have two options:

* If you have a paid support contract, please open a ticket in your account portal: account.fusionauth.io/account/support
* If you do not, please post in the community forum: https://fusionauth.io/community/forum/

I'm closing this issue as a support request.

**Comment by MohMehrnia** [comment]
I use the community version and I need used API in C# for add user into group

**Comment by mooreds** [comment]
Awesome, please post your question in the community forum. That's the right place for it.
