### ISSUE TITLE
Provide FusionAuthClient constructor that accepts IRESTClientBuilder

### ISSUE THREAD

**Issue by AlexeyRaga** [FusionAuth/fusionauth-netcore-client#63]
It'd be beneficial to have a constructor on `FusionAuthClient` that would also accept `IRestClientBuilder` instead of always constructing the default one.

**Comment by mooreds** [comment]
Thanks for filing the issue.

Seems like a straightforward change to https://github.com/FusionAuth/fusionauth-netcore-client/blob/master/fusionauth-netcore-client/src/io/fusionauth/FusionAuthClient.cs#L43

Would you like to submit a PR?

**Comment by AlexeyRaga** [comment]
@mooreds I can if you find it acceptable. 
Just to double check: you don't generate it and I can update that class directly, right?

**Comment by mooreds** [comment]
Great question! I'm glad you asked @AlexeyRaga .

I double checked and it looks like it is generated here: https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/netcore.client.ftl#L44

But you should be able to make a PR against that adding a new constructor argument and I'll be able to merge that.

**Comment by AlexeyRaga** [comment]
@mooreds OK, I'll make a PR to https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/netcore.client.ftl#L44 soon then.

**Comment by AlexeyRaga** [comment]
@mooreds Done in https://github.com/FusionAuth/fusionauth-client-builder/pull/59

**Comment by AlexeyRaga** [comment]
@mooreds  Should we expect a release any time soon? ;)

**Comment by mooreds** [comment]
Don't have a firm date for the 1.43 release, plan is real soon now (tm). Sorry I can't be more specific, there are a few final fixes we're planning to get in to it.
