### ISSUE TITLE
Support for CancellationToken

### ISSUE THREAD

**Issue by Persistent13** [FusionAuth/fusionauth-netcore-client#68]
Hello!

I've been using this library, specifically the async bits, and I've found that none of them take a CancellationToken so that when a request is cancelled (e.g. user closes the tab in ASP.NET Core) the work being done by the library can be cancelled as well.

Without this, once the FusionAuth client starts processing a request, it will complete the work anyway, eating up server resources for unneeded results.

Is this something that's feasible to be added to this library?

**Comment by mooreds** [comment]
Hiya @Persistent13 ,

Except for a few calls, the FusionAuth API is synchronous. So the REST API underlying the client library would have to be adjusted to handle cancellation of API calls, which is a product change. If this is of interest to you, please file an issue in our general github issues repo: https://github.com/fusionauth/fusionauth-issues/issues and we'll see how much demand there is from the community.
